SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE text-001.

	SELECTION-SCREEN BEGIN OF LINE.
		SELECTION-SCREEN COMMENT 1(31) text-007 FOR FIELD p_par1.
		PARAMETERS: p_par1 TYPE werks_d.
		SELECTION-SCREEN COMMENT 52(5) text-008 FOR FIELD p_par2.
		PARAMETERS: p_par2 TYPE werks_d.
    SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK b1.